<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="7.3 Exception Idioms"-->
<LINK REL="stylesheet" href="FILES/sbolM.css">
</HEAD>
<BODY link="#354278" vlink="#000066" alink="#000080" topmargin="0">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="lpython_snode80.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="lpython_snode82.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
<FONT>
<h3>7.3
Exception Idioms</h3>


<p>We've seen the mechanics behind exceptions; now, let's
take look at some of the ways they're typically used.</p>




<H4>7.3.1
Exceptions Aren't Always a Bad Thing</H4>


<P>Python raises exceptions on errors, but not all exceptions are
errors. For instance, we saw in <A href="lpython_cnode17.html">Chapter 2</A>, that
file object <TT Class="monofont">read</TT> methods return empty strings at
the end of a file. Python also provides a built-in function called
<TT class="monofont">raw_input</tt>
<a name="idx602"></a>
for reading from the standard input stream; unlike file methods,
<tt class="monofont">raw_input</Tt> raises<A namE="idx603"></a> the built-in
<TT cLAsS="monofont">EOFError</tT> at end of file, instead of returning an
empty string (an empty string means an empty line when
<TT Class="monofont">raw_input</TT> is used). Because of that,
<TT clasS="monofont">raw_input</TT> often appears wrapped in a
<Tt claSS="monofont">try</TT> handler and nested in a loop, as in the
following code</p>



<pre class="monofont">while 1:
    try:
        line = raw_input()     # read line from stdin
    except EOFError:
        break                  # exit loop at end of file
    else:
<pre><i>            Process next 'line' here</i></pre></pre>






<H4>7.3.2
Searches Sometimes Signal Success by raise</h4>


<P>User-defined exceptions can signal nonerror conditions also. For
instance, a <a naMe="idx604"></A>search routine can be coded to raise
an exception when a match is found, instead of returning a status
flag that must be interpreted by the caller. In the following, the
<Tt CLaSs="monofont">try/except/else</TT> exception handler does the work of
an<TT clasS="monofont"> if/else</TT> return value tester:</P>



<pre cLASS="monofont">Found = "Item found"

def searcher():
<pre><i>    raise Found or return</I></PRE></pre>


<pre class="monofont">try:
    searcher()
except Found:              # exception if item was found
<pre><i>    Success</i></pre></pRe>


<Pre cLaSS="monofont">else:                      # else returned: not found
<pRE><i>    Failure</I></pRE></PRe>






<h4>7.3.3
Outer try Statements Can Debug Code</h4>


<p>You can also make use of exception handlers to replace Python's
default top-level exception-handling behavior seen previously. By
wrapping an entire program (or a call to it) in
an<A NAMe="idx605"></a> <a nAME="idx606"></A> outer <tt clASS="monofont">try</Tt>, you can catch
any exception that may occur while your program runs, thereby
subverting the default program termination. In the following, the
empty <tt class="monofont">except</tt> clause catches any uncaught exception
raised while the program runs. To get hold of the actual exception
that occurred, fetch the <tt class="monofont">exc_type</tt> and
<tT cLass="monofont">exc_value</Tt> attributes from the built-in
<TT cLAsS="monofont">sys</tT> module; they're automatically set to the
current exception's name and extra data:<FONt sizE="1"><SUP><a hreF="#FOOTNOTE-4">[4]</A></SUp></fonT>
</P>


<BLockquote><font size="1">
<p claSs="footnote">
<Sup><a NaME="FOOTNOTE-4">[4]</a></SUp>
By the
way, the built-in <Tt CLASs="monofont">traceback</tt> module allows the
current exception to be processed in a generic fashion, and as of
Python 1.5.1, a new <tT CLAss="monofont">sys.exc_info()</tt> function
returns a tuple containing the current exception's type, data,
and traceback. <TT CLass="monofont">sys.exc_type</tT> and
<TT Class="monofont">sys.exc_value</tt> still work, but manage a single,
global exception; <tt class="monofont">exc_info()</tt> keeps track of each
thread's exception information and so is thread-specific. This
distinction matters only when using multiple threads in Python
programs (a subject beyond this book's scope). See the Python
library manual for more details.</p>
</font></BlOckqUoTE>





<pRE cLaSS="monofont">try:
<PRe><i>    Run program</i></pRE></PRe>


<pre CLASs="monofont">except:              # all uncaught exceptions come here
    import sys
    print 'uncaught!', sys.exc_type, sys.exc_value</pre>

</FONT>
 
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="lpython_snode80.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="lpython_snode82.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
</BODY></HTML>