<html>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<head>
<title>Section 10.2.&nbsp; Exceptions in Python</title>
<link rel="STYLESHEET" type="text/css" href="images/style.css">
<link rel="STYLESHEET" type="text/css" href="images/docsafari.css">
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td><div STYLE="MARGIN-LEFT: 0.15in;">
<a href=ch10lev1sec1.html><img src="images/prev.gif" width="60" height="17" border="0" align="absmiddle" alt="Previous Page"></a>
<td align="right"><div STYLE="MARGIN-LEFT: 0.15in;">
<a href=ch10lev1sec3.html><img src="images/next.gif" width="60" height="17" border="0" align="absmiddle" alt="Next Page"></a>
</div></td></tr></table>
<br><table width="100%" border="0" cellspacing="0" cellpadding="0"><tr><TD valign="top"><a name="ch10lev1sec2"></a>
<h3 id="title-IDA4L45H" class="docSection1Title">10.2. Exceptions in Python</H3>
<p class="docText">As you were going through some of the examples in the previous chapters, you no doubt noticed what happens when your program &quot;crashes&quot; or terminates due to unresolved errors. A &quot;traceback&quot; notice appears along with a notice containing as much diagnostic information as the interpreter can give you, including the error name, reason, and perhaps even the line number near or exactly where the error occurred. All errors have a similar format, regardless of <a name="iddle3033"></a><a name="iddle4107"></a><a name="iddle4559"></a>whether running within the Python interpreter or standard script execution, providing a consistent error interface. All errors, whether they be syntactical or logical, result from behavior incompatible with the Python interpreter and cause exceptions to be raised.</p>
<p class="docText">Let us take a look at some exceptions now.</P>
<p class="docText"><span class="docEmphStrong"><tt>NameError:</tt></span> <span class="docEmphBoldItalic">attempt to access an undeclared variable</span></P>
<div class="docText"><pre>&gt;&gt;&gt; foo
Traceback (innermost last):
 File "&lt;stdin&gt;", line 1, in ?
NameError: name 'foo' is not defined</pre></div><BR>
<p class="docText"><span class="docEmphasis"><tt>NameError</tt></span> indicates access to an uninitialized variable. The offending identifier was not found in the Python interpreter's symbol table. We will be discussing <span class="docEmphasis">namespaces</span> in the next two chapters, but as an introduction, regard them as &quot;address books&quot; linking names to objects. Any object that is accessible should be listed in a namespace. Accessing a variable entails a search by the interpreter, and if the name requested is not found in any of the namespaces, a <span class="docEmphasis"><tt>NameError</tt></span> exception will be generated.</P>
<p class="docText"><span class="docEmphStrong"><tt>ZeroDivisionError:</tt></span> <span class="docEmphBoldItalic">division by any numeric zero</span></p>
<div class="docText"><pre>&gt;&gt;&gt; 1/0
Traceback (innermost last):
 File &quot;&lt;stdin&gt;&quot;, line 1, in ?
ZeroDivisionError: integer division or modulo by zero</pre></div><br>
<p class="docText">Our example above used floats, but in general, any numeric division-by-zero will result in a <span class="docEmphasis"><tt>ZeroDivisionError</tt></span> exception.</p>
<p class="docText"><span class="docEmphStrong"><tt>SyntaxError:</tt></span> <span class="docEmphBoldItalic">Python interpreter syntax error</span></P>
<div class="docText"><pre>&gt;&gt;&gt; <span class="docEmphStrong">for</span>
  File &quot;&lt;string&gt;&quot;, line 1
    <span class="docEmphStrong">for</span>
       ^
SyntaxError: invalid syntax</pre></div><br>
<p class="docText"><tt>SyntaxError</tt> exceptions are the only ones that do not occur at run-time. They indicate an improperly constructed piece of Python code which cannot execute until corrected. These errors are generated at compile-time, when the interpreter loads and attempts to convert your script to Python bytecode. These may also occur as a result of importing a faulty module.</P>
<p class="docText"><a name="iddle1179"></a><a name="iddle2408"></a><a name="iddle2537"></a><a name="iddle2601"></a><span class="docEmphStrong"><tt>IndexError:</tt></span> <span class="docEmphBoldItalic">request for an out-of-range index for sequence</span></p>
<div class="docText"><pre>&gt;&gt;&gt; aList = []
&gt;&gt;&gt; aList[0]
Traceback (innermost last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in ?
IndexError: list index out of range</pre></div><BR>
<p class="docText"><tt>IndexError</tt> is raised when attempting to access an index that is outside the valid range of a sequence.</p>
<p class="docText"><span class="docEmphStrong"><tt>KeyError:</tt></span> <span class="docEmphBoldItalic">request for a non-existent dictionary key</span></P>
<div class="docText"><pre>&gt;&gt;&gt; aDict = {'host': 'earth', 'port': 80}
&gt;&gt;&gt; <span class="docEmphStrong">print</span> aDict['server']
Traceback (innermost last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in ?
KeyError: server</pre></div><BR>
<p class="docText">Mapping types such as dictionaries depend on keys to access data values. Such values are not retrieved if an incorrect/nonexistent key is requested. In this case, a <tt>KeyError</tt>is raised to indicate such an incident has occurred.</p>
<p class="docText"><span class="docEmphStrong"><tt>IOError:</tt></span> <span class="docEmphBoldItalic">input/output error</span></p>
<div class="docText"><pre>&gt;&gt;&gt; f = open(&quot;blah&quot;)
Traceback (innermost last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in ?
IOError: [Errno 2] No such file or directory: 'blah'</pre></div><br>
<p class="docText">Attempting to open a nonexistent disk file is one example of an operating system input/output (I/O) error. Any type of I/O error raises an <tt>IOError</tt> exception.</p>
<p class="docText"><span class="docEmphStrong"><tt>AttributeError:</tt></span> <span class="docEmphBoldItalic">attempt to access an unknown object attribute</span></P>
<div class="docText"><pre>&gt;&gt;&gt; <span class="docEmphStrong">class</span> myClass(object):
...      <span class="docEmphStrong">pass</span>
...
&gt;&gt;&gt; myInst = myClass()
&gt;&gt;&gt; myInst.bar = 'spam'
&gt;&gt;&gt; myInst.bar
'spam'
&gt;&gt;&gt; myInst.foo
Traceback (innermost last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in ?
AttributeError: foo</pre></div><br>
<p class="docText"><a name="iddle1854"></a><a name="iddle1874"></a><a name="iddle4233"></a><a name="iddle4532"></a>In our example, we stored a value in <tt>myInst.bar</tt>, the <tt>bar</tt> attribute of instance <tt>myInst</tt>. Once an attribute has been defined, we can access it using the familiar dotted-attribute notation, but if it has not, as in our case with the <tt>foo</tt> (non-)attribute, an <tt>AttributeError</tt> occurs.</p>

<a href="14051536.html"><img src="images/pixel.jpg" alt="" width="1" height="1" border="0"></a></TD></TR></table>
<br>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td><div STYLE="MARGIN-LEFT: 0.15in;">
<a href=ch10lev1sec1.html><img src="images/prev.gif" width="60" height="17" border="0" align="absmiddle" alt="Previous Page"></a>
<td align="right"><div STYLE="MARGIN-LEFT: 0.15in;">
<a href=ch10lev1sec3.html><img src="images/next.gif" width="60" height="17" border="0" align="absmiddle" alt="Next Page"></a>
</div></td></tr></table>
</body></html>