<html><head>
<META http-equiv="Content-Type" content="text/html">
<!--SafClassName="docChapterTitle"--><!--SafTocEntry="Chapter 6. Exceptions"-->
<link rel="STYLESHEET" type="text/css" href="FILES/style.css">
<link rel="STYLESHEET" type="text/css" href="FILES/docsafari.css">
<style type="text/css">	.tt1    {font-size: 10pt;}</style>
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<td class="tt1"><a href="NFO/lib.html">[ Team LiB ]</a></td><td valign="top" class="tt1" align="right">
	<a href="0596001886_pythonian-chp-5-sect-4.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
	<a href="0596001886_pythonian-chp-6-sect-1.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</td></table>
<br>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td valign="top"><A NAME="pythonian-CHP-6"></A>
<H2 class="docChapterTitle">Chapter 6. Exceptions</H2>



<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4551"></A>Python
uses exceptions to communicate errors and anomalies. An
<I>exception</I> is an object that indicates an error
or anomalous condition. When Python detects an error, it raises an
exception; that is, it signals the occurrence of an anomalous
condition by passing an exception object to the exception-propagation
mechanism. Your code can also explicitly raise an exception by
executing a <TT>raise</TT> statement.</P>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4552"></A>
<A NAME="pythonian-CHP-6-ITERM-4553"></A> <A NAME="pythonian-CHP-6-ITERM-4554"></A>Handling an exception means receiving
the exception object from the propagation mechanism and performing
whatever actions are needed to deal with the anomalous situation. If
a program does not handle an exception, it terminates with an error
traceback message. However, a program can handle exceptions and keep
running despite errors or other abnormal conditions.</P>

<P class="docText">Python also uses exceptions to indicate some special situations that
are not errors, and are not even abnormal occurrences. For example,
as covered in <A class="docLink" HREF="0596001886_pythonian-chp-4.html#pythonian-CHP-4">Chapter 4</A>, an
iterator's <TT>next</TT> method raises the
exception <TT>StopIteration</TT> when the iterator has no
more items. This is not an error, and it is not even an anomalous
condition, since most iterators run out of items eventually.</P>



<ul></ul>
</td>
</tr>
</table>
<td></td>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<td class="tt1"><a href="NFO/lib.html">[ Team LiB ]</a></td><td valign="top" class="tt1" align="right">
          <a href="0596001886_pythonian-chp-5-sect-4.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
          <a href="0596001886_pythonian-chp-6-sect-1.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</td></table>
</body></html>
